module.exports = {
  add:       require('./add'),
  arange:    require('./arange'),
  argmax:    require('./argmax'),
  dimension: require('./dimension'),
  dim:       require('./dimension'),
  divide:    require('./divide'),
  div:       require('./divide'),
  dot:       require('./dot'),
  flatten:   require('./flatten'),
  max:       require('./max'),
  min:       require('./min'),
  multiply:  require('./multiply'),
  mul:       require('./multiply'),
  outer:     require('./outer'),
  subset:    require('./subset'),
  subtract:  require('./subtract'),
  sub:       require('./subtract'),
  sum:       require('./sum'),
  transpose: require('./transpose'),
  T:         require('./transpose')
}
